PREFIX foaf: <http://xmlns.com/foaf/0.1/>

ASK WHERE {
  <http://greggkellogg.net/foaf#me> foaf:knows <http://www.ivan-herman.net/foaf#me> .
  <http://www.ivan-herman.net/foaf#me> foaf:name "Herman Iv\u00E1n"@hu .
}