PREFIX ex: <http://example.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK
WHERE {
  ex:ParisFact1 a rdf:Graph;
    ex:hasReference <http://www.britannica.com/>,
      <http://www.wikipedia.org/>,
      <http://www.brockhaus.de/> .
  ex:ParisFact2 a rdf:Graph;
    ex:hasReference <http://www.wikipedia.org/> .
  GRAPH ex:ParisFact1 {
    <http://example.org/location/Paris#this> ex:locatedIn <http://example.org/location/France#this> .
  }
  GRAPH ex:ParisFact2 {
    <http://example.org/location/Paris#this> ex:locatedIn <http://example.org/location/France#this> .
  }
}
