PREFIX dc: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sec: <http://purl.org/security#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK WHERE {
  <http://example.org/sig1> a rdf:Graph, sec:SignedGraph;
    dc:created "2011-09-23T20:21:34Z"^^xsd:dateTime;
    sec:signatureValue "OGQzNGVkMzVm4NTIyZTkZDYMmMzQzNmExMgoYzI43Q3ODIyOWM32NjI=";
    sec:signer <http://payswarm.example.com/i/john/keys/5> .
  GRAPH <http://example.org/sig1> {
    <http://example.org/fact1> dc:title "Hello World!" .
  }
}
